import SwiftUI

/// Inline view displayed in the transcript area when an automation action occurs.
///
/// Styled distinctly from transcript segments to indicate it was generated by Gophy.
@MainActor
struct AutomationActivityView: View {
    let event: AutomationEvent

    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: iconName)
                .foregroundStyle(iconColor)
                .font(.caption)
                .frame(width: 16)

            VStack(alignment: .leading, spacing: 2) {
                Text(headerText)
                    .font(.caption)
                    .fontWeight(.medium)
                    .italic()
                    .foregroundStyle(.blue)

                if let detail = detailText {
                    Text(detail)
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                        .italic()
                        .lineLimit(2)
                }
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.blue.opacity(0.08))
        .cornerRadius(6)
    }

    private var iconName: String {
        switch event {
        case .triggered: return "bolt.fill"
        case .executing: return "gearshape.fill"
        case .completed: return "checkmark.circle.fill"
        case .confirmationNeeded: return "questionmark.circle.fill"
        case .failed: return "exclamationmark.triangle.fill"
        }
    }

    private var iconColor: Color {
        switch event {
        case .triggered: return .blue
        case .executing: return .secondary
        case .completed: return .green
        case .confirmationNeeded: return .yellow
        case .failed: return .orange
        }
    }

    private var headerText: String {
        switch event {
        case .triggered(let name, let source):
            let sourceLabel = source == .voiceCommand ? "voice" : "shortcut"
            return "[Gophy] \(displayName(name)) triggered via \(sourceLabel)"
        case .executing(let name):
            return "[Gophy] Running \(displayName(name))..."
        case .completed(let name, _):
            return "[Gophy] \(displayName(name)) completed"
        case .confirmationNeeded(let toolCall):
            return "[Gophy] \(displayName(toolCall.function.name)) needs confirmation"
        case .failed(let name, _):
            return "[Gophy] \(displayName(name)) failed"
        }
    }

    private var detailText: String? {
        switch event {
        case .completed(_, let result):
            return result.isEmpty ? nil : result
        case .failed(_, let error):
            return error
        default:
            return nil
        }
    }

    private func displayName(_ toolName: String) -> String {
        switch toolName {
        case "remember": return "Remember"
        case "take_note": return "Note"
        case "generate_summary": return "Summary"
        case "search_knowledge": return "Search"
        default: return toolName
        }
    }
}
